[package]
name = "synchro"
version = "0.1.0"
authors = ["jurplel <jurplel@interversehq.com>"]
edition = "2018"
license = "MIT"

[dependencies]
libsynchro = { version = "0.1.0", path = "../" }

[build-dependencies]
cbindgen = "0.9"

[lib]
crate-type = ["cdylib", "staticlib"]